### PR TITLE
Removed generic from ReloadFromDataProviderSources.

### PR DESCRIPTION
**Pull request by LinusCenterstrom**
Implemented ReloadFromSources in null data provider (as noop).
Added method to remove all translation reloaded listeneres. (Needed for tests)

### CODE REVIEW

**Comment by LinusCenterstrom** [comment]
> Would you kindly add `[ThreadStatic]` on `Instance` in `L10n.cs`.
Wouldn't that break webprojects since requests are handled on multiple threads?

**Comment by itssimple** [comment]
I don't think there should be a problem. 

But it should remove the problem with using the `TemporaryLanguageProvider`, which sometimes doesn't return to the original `IL10nLanguageProvider`

**Comment by LinusCenterstrom** [comment]
L10n.CreateInstance would need to be called once per thread or the Instance will be null, no?

**Comment by itssimple** [comment]
tbf, I haven't tried. But I can try it locally after we merge this otherwise :)

**Pull request merged**
